# Site settings
title: TechSupports
email:
description: >
baseurl: ""
url: "http://techsupports.org"
twitter_username: techsupportsorg
github_username: techsupportsorg

# Build settings
markdown: kramdown
