# Site settings
title: TechSupports
email:
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://techsupports.org" # the base hostname & protocol for your site

twitter_username:techsupportsorg
github_username:techsupportsorg

# Build settings
markdown: kramdown
